#ifndef OPM_GENERATED_OPM_TIMESTAMP_HEADER_INCLUDED
#define OPM_GENERATED_OPM_TIMESTAMP_HEADER_INCLUDED
#define BUILD_TIMESTAMP "2026-02-27 at 16:22:36 hrs"
#endif // OPM_GENERATED_OPM_TIMESTAMP_HEADER_INCLUDED
